name: CI (CUDA, win-x64) x79-c600 ivy-bridge rtx-ampere

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ github.token }}
  GGML_NLOOP: 3
  GGML_N_THREADS: 1
  LLAMA_ARG_LOG_COLORS: 1
  LLAMA_ARG_LOG_PREFIX: 1
  LLAMA_ARG_LOG_TIMESTAMPS: 1

jobs:
  cuda:
    name: windows-cuda-12.4-x64-sm86
    runs-on: windows-2022

    permissions:
      actions: write

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v6

      - name: ccache
        uses: ggml-org/ccache-action@v1.2.21
        with:
          key: x79-c600-windows-2022-x64-cuda-12.4-sm86

      - name: Install Cuda Toolkit
        uses: ./.github/actions/windows-setup-cuda
        with:
          cuda_version: '12.4'
          cuda_arch: x64

      - name: Install Ninja
        id: install_ninja
        shell: pwsh
        run: |
          choco install ninja -y

      - name: Build
        id: cmake_build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64

          cmake -S . -B build -G "Ninja Multi-Config" ^
            -DGGML_BACKEND_DL=ON ^
            -DGGML_NATIVE=OFF ^
            -DGGML_CPU=ON ^
            -DGGML_CUDA=ON ^
            -DGGML_CUDA_CUB_3DOT2=ON ^
            -DCMAKE_CUDA_ARCHITECTURES=86 ^
            -DLLAMA_BUILD_SERVER=ON ^
            -DLLAMA_BUILD_BORINGSSL=ON

          set /A NINJA_JOBS=%NUMBER_OF_PROCESSORS%-1
          cmake --build build --config Release -j %NINJA_JOBS%

      - name: Test
        id: cmake_test
        shell: cmd
        run: |
          cd build
          ctest -L main -C Release --verbose --timeout 900

      - name: Package
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist | Out-Null

          Copy-Item `
            "build/bin/Release/*" `
            "dist/" `
            -Recurse `
            -Force

          Compress-Archive `
            -Path "dist/*" `
            -DestinationPath "x79-c600-cuda-12.4-sm86-windows-x64.zip" `
            -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: llama-win-x64-x79-c600-cuda-12.4-sm86-hardened
          path: llama-win-x64-x79-c600-cuda-12.4-sm86-hardened.zip
          if-no-files-found: error

      - name: ccache-clear
        uses: ./.github/actions/ccache-clear
        with:
          key: x79-c600-windows-2022-x64-cuda-12.4-sm86
